on:
  push:
    paths:
      - '.github/workflows/auto_build.yml'
      - 'main.py'
      - 'requirements.txt'
      - 'wkhtmltopdf'
      - 'wkhtmltopdf.exe' 

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install required dependencies
        run: pip install -r requirements.txt pyinstaller
      
      - name: Build
        run: pyinstaller --add-binary "wkhtmltopdf:." -F "main.py" -n olm-${{ github.run_number }}
      
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: olm-${{ github.run_number }}
          path: dist/olm-${{ github.run_number }}
  
  Windows:
    runs-on: windows-latest
    
    needs: Ubuntu

    steps:
      - uses: actions/checkout@v3

      - name: Download Linux artifact
        uses: actions/download-artifact@v3
        with:
          name: olm-${{ github.run_number }}
          path: dist
      
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install required dependencies
        run: pip install -r requirements.txt pyinstaller
      
      - name: Build
        run: pyinstaller --add-binary "wkhtmltopdf.exe:." -F "main.py" -n olm-${{ github.run_number }}.exe
        
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: olm-${{ github.run_number }}.exe
          path: dist/olm-${{ github.run_number }}.exe
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
          tag_name: OLM#${{ github.run_number }}

        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

